// <auto-generated />
using System;
using Billing.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Billing.Infastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Billing.Infastructure.APICallLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APIServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("CallThrough")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("APICallLogs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 2L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 3L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 4L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 5L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 6L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 7L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 8L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 9L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 10L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 11L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 12L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 13L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 14L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 15L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 16L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 17L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 18L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 19L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 20L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 21L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 22L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 23L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 24L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 25L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 26L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 27L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 28L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 29L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 30L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 31L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 32L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 33L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 34L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 35L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 36L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 37L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 38L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 39L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 40L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 41L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 42L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "MTN"
                        },
                        new
                        {
                            Id = 43L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 44L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 45L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 46L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "STANBIC"
                        },
                        new
                        {
                            Id = 47L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = false,
                            CustomerName = "INTERSWITCH"
                        },
                        new
                        {
                            Id = 48L,
                            APIServiceId = "SAPI09-0982",
                            CallDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CallThrough = true,
                            CustomerName = "INTERSWITCH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
